plugins:
  - prettier-plugin-svelte
  - prettier-plugin-astro
  - prettier-plugin-tailwindcss
overrides:
  - files: "*.svelte"
    options:
      parser: "svelte"
  - files: "*.astro"
    options:
      parser: "astro"
