* kemdict

Kemdict 整合了多部辭典，提供一次搜尋的功能。

目前整合的辭典：

- [[如月的現代台灣華語補足典]]
- 重編國語辭典（透過[[https://language.moe.gov.tw/001/Upload/Files/site_content/M0001/respub/index.html][辭典公眾授權網]]）
- 臺灣台語常用詞辭典（透過[[https://github.com/kemdict/kemdict-data-ministry-of-education][kemdict-data-ministry-of-education]]）
- 臺灣客家語常用詞辭典（透過[[https://hakkadict.moe.edu.tw/cgi-bin/gs32/gsweb.cgi/ccd=dpViqL/newsresult_format0?r1=1&searchall=1][客家語常用詞辭典文字內容下載公告]]）
- 成語典（透過[[https://language.moe.gov.tw/001/Upload/Files/site_content/M0001/respub/index.html][辭典公眾授權網]]）
- 國語辭典簡編本（透過[[https://language.moe.gov.tw/001/Upload/Files/site_content/M0001/respub/index.html][辭典公眾授權網]]）
- iTaigi 華台對照典（透過[[https://github.com/ChhoeTaigi/ChhoeTaigiDatabase][ChhoeTaigi 台語字詞資料庫]]）
- 台日大辭典台語譯本（透過[[https://github.com/ChhoeTaigi/ChhoeTaigiDatabase][ChhoeTaigi 台語字詞資料庫]]）
- [[https://mhi.moe.edu.tw/infoList.jsp?ID=2&ID2=1705][台灣白話基礎語句]]（透過[[https://github.com/ChhoeTaigi/ChhoeTaigiDatabase][ChhoeTaigi 台語字詞資料庫]]）
- [[https://thak.taigi.info/1928TaioanSitbutMialui/][臺灣植物名彙]]（透過[[https://kisaragi-hiu.com/list-of-plants-of-formosa/][我的數位化]]）
- Unihan（透過 [[https://unihan-etl.git-pull.com/][unihan-etl]]）

我希望整合的辭典：

- …

我不計劃整合的辭典：

- 維基詞典：太大、重編國語辭典就夠了

** 如月的現代台灣華語補足典

現代台灣華語有些詞教育部沒有收。我生活中遇到時總會覺得缺一角。這個「字典」是我記錄的詞。

詳細說明：https://kemdict.com/dict-kisaragi

** Building

The data will be built at the same time.

Clone submodules recursively, then

#+begin_src shell
cd dicts
make entries.db
#+end_src

** 建置

各個資料夾之後會有更新的說明。

建置需求：

- Emacs (27 ~ 28), to combine the data sources
- Make
- Node, npm
- [[https://github.com/cask/cask][Cask]], to get Emacs Lisp dependencies

#+begin_src shell
# also installs dependencies for all subprojects thanks to workspaces
npm install
# This handles building the dictionaries as part of its dependencies
cd web && make build
#+end_src

Dictionary sources are used through git submodules, fetched automatically by Make if not present.

The output directory is at =web/build=.

** License

教育部重編國語字典著作權為中華民國教育部所有，[[https://language.moe.gov.tw/001/Upload/Files/site_content/M0001/respub/index.html][使用「創用CC-姓名標示- 禁止改作 3.0 臺灣授權條款」]]。

教育部臺灣台語常用詞辭典著作權亦為中華民國教育部所有，[[https://sutian.moe.edu.tw/zh-hant/piantsip/pankhuan-singbing/][使用「創用CC-姓名標示- 禁止改作 3.0 臺灣授權條款」]]。資料處理位於[[https://github.com/kemdict/kemdict-data-ministry-of-education][kemdict-data-ministry-of-education]]，原先參考[[https://github.com/g0v/moedict-data-twblg][moedict-data-twblg]]。

本專案其餘著作權由我（如月飛羽）以 CC0 釋出，內文見[[./LICENSE-CC0][LICENSE-CC0]]。
