(package "x" "0.0.0" "x")

(source "melpa")
(source "gnu")

(depends-on "dash")
(depends-on "s")
(depends-on "ht")
(depends-on "jieba"
            :fetcher 'github
            :repo "kisaragi-hiu/emacs-jieba")
