name: Build data

on:
  push:
    branches:
      - main
    paths:
      - "dicts/**"
      # For kisaragi-dict, we commit the JSON together, so this is fine
      - "!*.org"
  workflow_dispatch:

jobs:
  "build":
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install packages
        run: |
          cd dicts
          pip install unihan-etl typing_extensions
          # unihan-etl uses Unihan.zip from latest Unicode, but right
          # now does not appear to work with Unihan.zip from Unicode
          # 15.1. It did work with the one from Unicode 15.0, so use
          # that instead.
          mkdir -p ~/.cache/unihan_etl/downloads
          curl -L https://www.unicode.org/Public/15.0.0/ucd/Unihan.zip > ~/.cache/unihan_etl/downloads/Unihan.zip
      - name: Set up Emacs
        uses: purcell/setup-emacs@master
        with:
          version: 29.1
      - uses: emacs-eask/setup-eask@master
        with:
          version: "snapshot"
      - name: Set up SSH
        env:
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
          SSH_SECRET: ${{ secrets.SSH_SECRET }}
        run: |
          mkdir -p ~/.ssh
          printenv SSH_KNOWN_HOSTS >> ~/.ssh/known_hosts
          printenv SSH_SECRET > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
      - name: Build data files
        run: |
          cd dicts
          eask install-deps
          make entries.db.gz
      - name: Deploy built database
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
        run: |
          cd dicts
          make admin.deploy
        shell: bash
