name: Test Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  "build-macos":
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
      # - name: Set up Emacs
      #   uses: purcell/setup-emacs@master
      #   with:
      #     version: "28.2"
      # - name: Set up Cask
      #   uses: conao3/setup-cask@master
      - name: Install packages
        run: |
          brew install cask make emacs
          cask install
          npm install
        # These steps are split to get them to display in different
        # sections. make _site alone also builds src/_data.
      - name: Prepare data files
        run: make src/_data
      - name: Build
        run: gmake _site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./_site
  "build":
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
      - name: Set up Emacs
        uses: purcell/setup-emacs@master
        with:
          version: "28.2"
      - name: Set up Cask
        uses: conao3/setup-cask@master
      - name: Set up Pages
        id: pages
        uses: actions/configure-pages@v2
      - name: Install packages
        run: |
          cask
          npm install
      - name: Raise file limits
        run: |
          sudo sysctl -w fs.file-max=500000
        # These steps are split to get them to display in different
        # sections. make _site alone also builds src/_data.
      - name: Prepare data files
        run: make src/_data
      - name: Build
        run: sudo prlimit --nofile=400000 make gh-pages
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./_site
  "deploy":
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: "build"
    steps:
      - name: "Deploy to GitHub Pages"
        id: deployment
        uses: actions/deploy-pages@v1
