name: Deploy

on:
  push:
    branches:
      - main
  release:
    types:
      - published
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: "pages"
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  "build":
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Fetch tags for release purposes
        run: |
          git fetch --depth=1 --tags
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"
      - name: Set up Emacs
        # This is Emacs 27.1
        run: |
          sudo apt-get install emacs-nox
      - name: Set up Cask
        uses: conao3/setup-cask@master
      - name: Install packages
        run: |
          npm install
          (cd dicts && npm install)
          (cd dicts && cask)
          (cd web && npm install)
          (cd web && npm install netlify-cli)
      - name: Cache data files
        uses: actions/cache@v3
        with:
          path: "dicts/entries.db.gz"
          # key: dicts-${{ github.ref_name }}
          key: "dicts-${{ hashFiles('dicts/**') }}"
          restore-keys: |
            dicts-
      - name: Prepare data files
        run: |
          cd dicts
          make entries.db.gz
      - name: Build
        run: |
          cd web
          make build
      - name: Deploy to Netlify
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: |
          cd web
          netlify deploy --dir=build --prod
