name: Deploy web

on:
  push:
    branches:
      - main
    paths:
      - "web/**"
      - "common/**"
      - "!*.org"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: "pages"
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  "build":
    runs-on: ubuntu-22.04
    steps:
      - name: Set up SSH
        env:
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
          SSH_SECRET: ${{ secrets.SSH_SECRET }}
        run: |
          mkdir -p ~/.ssh
          printenv SSH_KNOWN_HOSTS >> ~/.ssh/known_hosts
          printenv SSH_SECRET > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # dicts is not a submodule any more
          submodules: false
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install packages
        run: |
          cd web
          bun install
      - name: Build and deploy
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
        run: |
          make admin.deploy.kemdict
