name: Deploy web

on:
  push:
    branches:
      - main
    paths:
      - "web/**"
      - "common/**"
      - "!*.org"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: "pages"
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  "build":
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Set up SSH
        env:
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
          SSH_SECRET: ${{ secrets.SSH_SECRET }}
        run: |
          mkdir -p ~/.ssh
          printenv SSH_KNOWN_HOSTS >> ~/.ssh/known_hosts
          printenv SSH_SECRET > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
      - uses: pnpm/action-setup@v4
        with:
          version: 9.0.6
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"
          cache-dependency-path: "web/pnpm-lock.yaml"
      - name: Install packages
        run: |
          cd web
          pnpm install
      - name: Build and deploy
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
        run: |
          make admin.deploy.kemdict
