env:
  node: true
  browser: true
  es2022: true

ignorePatterns:
  - "node_modules"
  - "dist"

extends:
  - "eslint:recommended"
  - "plugin:astro/recommended"
  - "plugin:svelte/recommended"
  - "plugin:svelte/prettier"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:@typescript-eslint/recommended-requiring-type-checking"
  - "prettier"

parser: "@typescript-eslint/parser"
parserOptions:
  project: "./tsconfig.json"
  tsconfigRootDir: "."
  extraFileExtensions:
    - ".svelte"
    - ".astro"

overrides:
  - files: ["*"]
    rules:
      "no-irregular-whitespace": "off"
  - files: ["*.js"]
    rules:
      "no-unused-vars":
        - "warn"
        - &noUnusedVarsSetting
          argsIgnorePattern: "^_"
          destructuredArrayIgnorePattern: "^_"
  - files: ["*.ts"]
    parser: "@typescript-eslint/parser"
    rules: &TS
      "@typescript-eslint/no-unsafe-assignment": "off"
      "@typescript-eslint/no-unsafe-call": "off"
      "@typescript-eslint/no-unsafe-member-access": "off"
      "@typescript-eslint/no-unsafe-return": "off"
      "@typescript-eslint/no-explicit-any": "off"
      "@typescript-eslint/no-unused-vars":
        - "error"
        - *noUnusedVarsSetting
      "@typescript-eslint/restrict-template-expressions":
        - "error"
        - allowNumber: true
          allowBoolean: true
  - files: ["*.astro"]
    parser: "astro-eslint-parser"
    parserOptions:
      parser: "@typescript-eslint/parser"
    rules:
      # The database is fully trusted.
      "astro/no-set-html-directive": "off"
      <<: *TS
  - files: ["*.svelte"]
    parser: "svelte-eslint-parser"
    parserOptions:
      parser: "@typescript-eslint/parser"
    rules:
      # The database is fully trusted.
      "svelte/no-at-html-tags": "off"
      <<: *TS
